# Generated by Django 3.1.4 on 2022-01-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='status',
        ),
    ]
